### PR TITLE
Code of Conduct

### PR DESCRIPTION
**Pull request by megahbite**
Given the isolation and environment of Rails Camp, I feel it would be appropriate to have a code of conduct in place for attendees. This code of conduct is adapted from [Ruby Australia's one](http://ruby.org.au/code-of-conduct.html).

### CODE REVIEW

**Comment by malclocke** [comment]
@megahbite thanks for this.  It's actually on our agenda to draw this up and should have gone out as part of the ticket purchase process, apologies that that didn't happen.

I'm OK with this, I'll just give the other organisers a chance to look it over before we publish it.

cc @parndt @Aupajo

**Comment by parndt** [comment]
Seems very reasonable to me.

Thanks a lot!

**Comment by pat** [comment]
Great move to get this on the site - and doubly nice to know our content in AU was good enough to adapt :)

**Comment by malclocke** [comment]
Ok, seeing as one of our organisers is AWOL I am merging this now.

And apologies we didn't have this in place prior to the ticket sales, we should have done.  We will be sending an email to all attendees to ensure they retrospectively agree to abide by the code of conduct.

**Comment by Aupajo** [comment]
:+1: I'm back now, and I approve this commit whole-heartedly :) Thanks, @megahbite.

**Pull request merged**
